server:
  port: 8080

pumpkin:
  log:
    enabled: true
    console:
      enabled: true
    file:
      enabled: true
    exclude-paths:
      - /actuator/**
      - /favicon.ico
    level:
      default: INFO
      client4xx: WARN
      server5xx: ERROR
